export const CATEGORIES = [
  {
    id: "mountains",
    label: "Tog'li Joylar",
    emoji: "⛰️",
    color: "#6B7FD4",
    gradient: "from-slate-600 to-indigo-900",
    desc: "Chimgan, Beldersay va boshqa tog'lar",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
  },
  {
    id: "lakes",
    label: "Ko'l va Suv Havzalari",
    emoji: "🏞️",
    color: "#0EA5E9",
    gradient: "from-cyan-600 to-blue-900",
    desc: "Chorvoq, Aydar Ko'li va boshqalar",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80",
  },
  {
    id: "picnic",
    label: "Piknik Joylari",
    emoji: "🧺",
    color: "#4D7C5E",
    gradient: "from-green-600 to-emerald-900",
    desc: "Yashil yaylovlar va bog'lar",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&q=80",
  },
  {
    id: "fishing",
    label: "Baliq Ovlash",
    emoji: "🎣",
    color: "#0F766E",
    gradient: "from-teal-600 to-cyan-900",
    desc: "Suv havzalari va daryolar",
    image: "https://images.unsplash.com/photo-1504006833117-8886a355efbf?w=600&q=80",
  },
  {
    id: "hiking",
    label: "Piyoda Sayohat",
    emoji: "🥾",
    color: "#92400E",
    gradient: "from-amber-700 to-orange-900",
    desc: "Tog' yo'llari va marshrut",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&q=80",
  },
  {
    id: "desert",
    label: "Cho'l va Sahrolar",
    emoji: "🏜️",
    color: "#D97706",
    gradient: "from-yellow-600 to-orange-900",
    desc: "Qizilqum, Orol dengizi",
    image: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=600&q=80",
  },
];

export const PLACES = {
  mountains: [
    {
      id: 1,
      name: "Chimgan",
      region: "Toshkent viloyati",
      lat: 41.5467,
      lng: 70.0064,
      altitude: "2097 m",
      rating: 4.8,
      reviews: 2847,
      season: "Yil davomida",
      difficulty: "O'rtacha",
      distance: "80 km Toshkentdan",
      description: "Chimgan — O'zbekistonning eng mashhur tog' kurort joyi. Yozda piyoda yurishga, qishda esa chanada uchishga ideal. Kanatlift va ko'plab mehmonxonalar mavjud.",
      tags: ["Kanatlift", "Qish sporti", "Trekking", "Mehmonxona", "Kafe", "Foto"],
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
      color: "#6B7FD4",
    },
    {
      id: 2,
      name: "Beldersay",
      region: "Toshkent viloyati",
      lat: 41.5233,
      lng: 70.0811,
      altitude: "2200 m",
      rating: 4.7,
      reviews: 1234,
      season: "Dekabr–Mart (qish), Iyun–Sentabr",
      difficulty: "Qiyin",
      distance: "85 km Toshkentdan",
      description: "Beldersay — qishki chang'i kurort. Shimoliy yonbag'irda joylashgan bo'lib, uzoqroq qor qoladi. Professional chang'ichilar uchun ideal joy.",
      tags: ["Chang'i", "Snowboard", "Kanatlift", "Extreme", "Qor"],
      image: "https://images.unsplash.com/photo-1418985991508-e47386d96a71?w=800&q=80",
      color: "#818CF8",
    },
    {
      id: 3,
      name: "Ugam-Chatqol Milliy Bog'i",
      region: "Toshkent viloyati",
      lat: 41.6500,
      lng: 70.3500,
      altitude: "3309 m",
      rating: 4.9,
      reviews: 876,
      season: "May–Oktabr",
      difficulty: "Qiyin",
      distance: "100 km Toshkentdan",
      description: "Ugam-Chatqol — O'rta Osiyodagi eng katta milliy bog'lardan biri. Noyob flora va fauna, toza tog' daryolari va ko'llar bilan mashhur.",
      tags: ["Milliy bog'", "Trekking", "Fauna", "Daryolar", "Kampinq"],
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
      color: "#4ADE80",
    },
    {
      id: 4,
      name: "Zaamin Milliy Bog'i",
      region: "Jizzax viloyati",
      lat: 39.7000,
      lng: 68.4000,
      altitude: "2200 m",
      rating: 4.7,
      reviews: 654,
      season: "May–Sentabr",
      difficulty: "O'rtacha",
      distance: "280 km Toshkentdan",
      description: "Zaamin — O'zbekistonning janubiy tog' kurort markazi. Archa o'rmonlari, toza havo va shifobaxsh buloqlar bilan mashhur.",
      tags: ["Archa o'rmoni", "Kurort", "Sog'lomlashtirish", "Daryolar"],
      image: "https://images.unsplash.com/photo-1502786129293-79981df4e689?w=800&q=80",
      color: "#34D399",
    },
  ],
  lakes: [
    {
      id: 5,
      name: "Chorvoq Suv Ombori",
      region: "Toshkent viloyati",
      lat: 41.5760,
      lng: 70.0336,
      altitude: "920 m",
      rating: 4.8,
      reviews: 5621,
      season: "May–Sentabr",
      difficulty: "Oson",
      distance: "75 km Toshkentdan",
      description: "Chorvoq — O'zbekistonning eng mashhur dam olish joyi. Moviy suv, tog' manzerasi va ko'plab pansionatlar. Yozda minglab dam oluvchilar keladi.",
      tags: ["Suzish", "Qayiq", "Pansionat", "SUP board", "Baliq", "Kafe"],
      image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
      color: "#0EA5E9",
    },
    {
      id: 6,
      name: "Aydar Ko'li",
      region: "Navoiy viloyati",
      lat: 40.9000,
      lng: 66.9000,
      altitude: "242 m",
      rating: 4.6,
      reviews: 1876,
      season: "Aprel–Oktabr",
      difficulty: "Oson",
      distance: "360 km Toshkentdan",
      description: "Aydar Ko'li — cho'l o'rtasidagi ulkan ko'l. G'ayrioddiy manzara, toza suv va qum plyajlari. Cho'l safari va yuртlarda tunash imkoniyati.",
      tags: ["Cho'l safari", "Yuртда tunash", "Qum plyaj", "G'urob", "Flamingo"],
      image: "https://images.unsplash.com/photo-1439405326-b42525451c48?w=800&q=80",
      color: "#38BDF8",
    },
    {
      id: 7,
      name: "Tudakul Ko'li",
      region: "Buxoro viloyati",
      lat: 39.7500,
      lng: 64.4000,
      altitude: "230 m",
      rating: 4.4,
      reviews: 432,
      season: "Mart–Noyabr",
      difficulty: "Oson",
      distance: "550 km Toshkentdan",
      description: "Tudakul — Buxoro yaqinidagi ko'l. Qushlarning ko'pligi bilan mashhur, ornitologlar uchun ideal joy. Baliq ovlash va qushlarni kuzatish.",
      tags: ["Qush kuzatish", "Baliq", "Tabiat", "Ornitologiya"],
      image: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&q=80",
      color: "#7DD3FC",
    },
  ],
  picnic: [
    {
      id: 8,
      name: "Humsan Daryosi Qirg'og'i",
      region: "Toshkent viloyati",
      lat: 41.3500,
      lng: 69.9000,
      altitude: "850 m",
      rating: 4.6,
      reviews: 1243,
      season: "Aprel–Oktabr",
      difficulty: "Oson",
      distance: "55 km Toshkentdan",
      description: "Humsan — shahardan yaqin, tabiatning go'zal burchi. Daryo bo'yida shashlik qilish, oilaviy piknik uchun ideal. Ko'p dam olish joylari va choyxonalar bor.",
      tags: ["Daryo", "Shashlik", "Oila", "Choyxona", "Hovuz", "Soya"],
      image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80",
      color: "#4D7C5E",
    },
    {
      id: 9,
      name: "Bostanliq — Parkent",
      region: "Toshkent viloyati",
      lat: 41.1000,
      lng: 69.8700,
      altitude: "650 m",
      rating: 4.7,
      reviews: 2100,
      season: "Mart–Noyabr",
      difficulty: "Oson",
      distance: "60 km Toshkentdan",
      description: "Bostanliq tumani — ko'kalamzor vodiylar, olma bog'lari va toza daryo suvi. Bahor chog'ida gullab-yashnagan tog' yaylovlari piknik uchun ajoyib.",
      tags: ["Olma bog'i", "Daryo", "Yaylov", "Qo'y go'shti", "Ziyofat"],
      image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80",
      color: "#22C55E",
    },
  ],
  fishing: [
    {
      id: 10,
      name: "Chorvoq — Baliq Ovlash",
      region: "Toshkent viloyati",
      lat: 41.5600,
      lng: 70.0200,
      altitude: "920 m",
      rating: 4.7,
      reviews: 876,
      season: "Yil davomida",
      difficulty: "Oson",
      distance: "75 km Toshkentdan",
      description: "Chorvoq suvomborida karp, zander, trout va boshqa baliqlar ko'p. Maxsus baliq ovlash joylari va uskunalar ijarasi mavjud.",
      tags: ["Karp", "Zander", "Trout", "Uskunа", "Qayiq", "Tunash"],
      image: "https://images.unsplash.com/photo-1504006833117-8886a355efbf?w=800&q=80",
      color: "#0F766E",
    },
    {
      id: 11,
      name: "Sirdaryо — Baliq Ovlash",
      region: "Sirdaryo viloyati",
      lat: 40.8300,
      lng: 68.7100,
      altitude: "220 m",
      rating: 4.5,
      reviews: 543,
      season: "Mart–Noyabr",
      difficulty: "Oson",
      distance: "120 km Toshkentdan",
      description: "Sirdaryo daryosi — O'zbekistonning eng uzun daryosi. Turli baliq turlari: som, karp, xo'roz baliq. Tungi baliq ovlash ham mumkin.",
      tags: ["Som", "Karp", "Daryo", "Tungi ovlash", "Qayiq"],
      image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
      color: "#14B8A6",
    },
  ],
  hiking: [
    {
      id: 12,
      name: "Aktash — Trekking Marshruti",
      region: "Toshkent viloyati",
      lat: 41.6200,
      lng: 70.1500,
      altitude: "2800 m",
      rating: 4.9,
      reviews: 432,
      season: "Iyun–Sentabr",
      difficulty: "Qiyin",
      distance: "90 km Toshkentdan",
      description: "Aktash — tog' trekkingchilari uchun eng yaxshi marshrutlardan biri. Ko'hna qal'a haroblari, tog' ko'llari va ajoyib manzaralar.",
      tags: ["Trekking", "Qal'a", "Tog' ko'li", "Ekspeditsiya", "Kampinq"],
      image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&q=80",
      color: "#92400E",
    },
  ],
  desert: [
    {
      id: 13,
      name: "Qizilqum Sahrosi",
      region: "Navoiy viloyati",
      lat: 41.5000,
      lng: 63.5000,
      altitude: "200 m",
      rating: 4.8,
      reviews: 1234,
      season: "Sentabr–Aprel",
      difficulty: "O'rtacha",
      distance: "500 km Toshkentdan",
      description: "Qizilqum — Markaziy Osiyodagi eng katta qizil qumli sahro. Tunda osmondagi yulduzlar hayratlanarli. Tuya safari, yurt camps va cho'l ekotarizmi.",
      tags: ["Tuya safari", "Yurt camp", "Yulduzli osmon", "Qum barxanlari", "Safari"],
      image: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&q=80",
      color: "#D97706",
    },
  ],
};